name: cuttingeeg-sourcerec
channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - jupyterlab
  - ipywidgets
  - nibabel
  - nilearn
  - pooch
  - pip:
      - mne
      - pyvista
      - "pyvista[jupyter]"
      - trame
      - trame-client
      - trame-server
      - trame-vtk
      - trame-vuetify
      - nest_asyncio2